SACK:
  MINING:
    DISPLAY: "&aMining Sack"
    DEFAULT_STORAGE: 10000
    ITEM:
      VANILLA;COAL:
        FROM:
          - VANILLA;COAL_ORE;1
          - VANILLA;COAL_BLOCK;3
      MMOITEMS;MATERIAL:IRON_INGOT:
        FROM:
          - VANILLA;IRON_ORE;1
          - VANILLA;IRON_BLOCK;3
          - MMOITEMS;MATERIAL:IRON_INGOT;1
      VANILLA;GOLD_INGOT:
        FROM:
          - VANILLA;GOLD_ORE;1
          - VANILLA;GOLD_BLOCK;3
      VANILLA;DIAMOND:
        FROM:
          - VANILLA;DIAMOND_ORE;1
          - VANILLA;DIAMOND_BLOCK;3
      VANILLA;EMERALD:
        FROM:
          - VANILLA;EMERALD_ORE;1
          - VANILLA;EMERALD_BLOCK;3
  FARMING:
    DISPLAY: "&aFarming Sack"
    DEFAULT_STORAGE: 10000
    ITEM:
      VANILLA;WHEAT:
        FROM:
          - VANILLA;HAY_BALE;3
          - VANILLA;WHEAT;1
      VANILLA;BEETROOT:
        FROM:
          - VANILLA;BEETROOTS;1
      VANILLA;CARROT:
        FROM:
          - VANILLA;CARROTS;1
      VANILLA;POTATO:
        FROM:
          - VANILLA;POTATOES;1