SACK:
  MINING:
    DISPLAY: '&aMining Sack'
    DEFAULT_STORAGE: 10000
    ITEM:
      MMOITEMS;MATERIAL-COBBLESTONE:
        FROM:
          - VANILLA;COBBLESTONE;1;60
          - VANILLA;STONE;3;60
          - MMOITEMS;MATERIAL-COBBLESTONE;1;60
      MMOITEMS;MATERIAL-COAL:
        FROM:
          - VANILLA;COAL;1;80
          - VANILLA;COAL_ORE;1;80
          - VANILLA;COAL_BLOCK;9;80
          - MMOITEMS;MATERIAL-COAL;1;80
      MMOITEMS;MATERIAL-IRON_INGOT:
        FROM:
          - VANILLA;IRON_INGOT;1;100
          - VANILLA;IRON_ORE;1;100
          - VANILLA;IRON_BLOCK;9;100
          - MMOITEMS;MATERIAL-IRON_INGOT;1;100
      MMOITEMS;MATERIAL-GOLD_INGOT:
        FROM:
          - VANILLA;GOLD_INGOT;1;120
          - VANILLA;GOLD_ORE;1;120
          - VANILLA;GOLD_BLOCK;9;120
          - MMOITEMS;MATERIAL-GOLD_INGOT;1;120
      MMOITEMS;MATERIAL-DIAMOND:
        FROM:
          - VANILLA;DIAMOND;1;140
          - VANILLA;DIAMOND_ORE;1;140
          - VANILLA;DIAMOND_BLOCK;9;140
          - MMOITEMS;MATERIAL-DIAMOND;1;140
      MMOITEMS;MATERIAL-EMERALD:
        FROM:
          - VANILLA;EMERALD;1;160
          - VANILLA;EMERALD_ORE;1;160
          - VANILLA;EMERALD_BLOCK;9;160
          - MMOITEMS;MATERIAL-EMERALD;1;160
      MMOITEMS;MATERIAL-QUARTZ:
        FROM:
          - VANILLA;QUARTZ;1;180
          - VANILLA;NETHER_QUARTZ_ORE;1;180
          - MMOITEMS;MATERIAL-QUARTZ;1;180
      MMOITEMS;MATERIAL-NETHERITE_INGOT:
        FROM:
          - VANILLA;NETHERITE_INGOT;1;200
          - VANILLA;ANCIENT_DEBRIS;1;200
          - MMOITEMS;MATERIAL-NETHERITE_INGOT;1;200
  FARMING:
    DISPLAY: '&aFarming Sack'
    DEFAULT_STORAGE: 10000
    ITEM:
      MMOITEMS;MATERIAL-WHEAT:
        FROM:
          - VANILLA;WHEAT;1;60
          - MMOITEMS;MATERIAL-WHEAT;1;60
      MMOITEMS;MATERIAL-BEETROOT:
        FROM:
          - VANILLA;BEETROOTS;1;120
          - MMOITEMS;MATERIAL-BEETROOT;1;120
      MMOITEMS;MATERIAL-CARROT:
        FROM:
          - VANILLA;CARROTS;1;240
          - MMOITEMS;MATERIAL-CARROT;1;240
      MMOITEMS;MATERIAL-POTATO:
        FROM:
          - VANILLA;POTATOES;1;360
          - MMOITEMS;MATERIAL-POTATO;1;360
