SACK:
  MINING:
    DISPLAY: "&aMining Sack"
    DEFAULT_STORAGE: 10000
    ITEM:
      MMOITEMS;MATERIAL-COBBLESTONE:
        FROM:
          - VANILLA;COBBLESTONE;1;10
          - VANILLA;STONE;3;10
          - MMOITEMS;MATERIAL-COBBLESTONE;1;10
      MMOITEMS;MATERIAL-COAL:
        FROM:
          - VANILLA;COAL;1;20
          - VANILLA;COAL_ORE;1;20
          - VANILLA;COAL_BLOCK;9;20
          - MMOITEMS;MATERIAL-COAL;1;20
      MMOITEMS;MATERIAL-IRON_INGOT:
        FROM:
          - VANILLA;IRON_INGOT;1;30
          - VANILLA;IRON_ORE;1;30
          - VANILLA;IRON_BLOCK;9;30
          - MMOITEMS;MATERIAL-IRON_INGOT;1;30
      MMOITEMS;MATERIAL-GOLD_INGOT:
        FROM:
          - VANILLA;GOLD_INGOT;1;40
          - VANILLA;GOLD_ORE;1;40
          - VANILLA;GOLD_BLOCK;9;40
          - MMOITEMS;MATERIAL-GOLD_INGOT;1;40
      MMOITEMS;MATERIAL-DIAMOND:
        FROM:
          - VANILLA;DIAMOND;1;50
          - VANILLA;DIAMOND_ORE;1;50
          - VANILLA;DIAMOND_BLOCK;9;50
          - MMOITEMS;MATERIAL-DIAMOND;1;50
      MMOITEMS;MATERIAL-EMERALD:
        FROM:
          - VANILLA;EMERALD;1;60
          - VANILLA;EMERALD_ORE;1;60
          - VANILLA;EMERALD_BLOCK;9;60
          - MMOITEMS;MATERIAL-EMERALD;1;60
      MMOITEMS;MATERIAL-QUARTZ:
        FROM:
          - VANILLA;QUARTZ;1;70
          - VANILLA;NETHER_QUARTZ_ORE;1;70
          - MMOITEMS;MATERIAL-QUARTZ;1;70
      MMOITEMS;MATERIAL-NETHERITE_INGOT:
        FROM:
          - VANILLA;NETHERITE_INGOT;1;80
          - VANILLA;ANCIENT_DEBRIS;1;80
          - MMOITEMS;MATERIAL-NETHERITE_INGOT;1;80
  FARMING:
    DISPLAY: "&aFarming Sack"
    DEFAULT_STORAGE: 10000
    ITEM:
      MMOITEMS;MATERIAL-WHEAT:
        FROM:
          - VANILLA;WHEAT;1;30
          - MMOITEMS;MATERIAL-WHEAT;1;30
      MMOITEMS;MATERIAL-BEETROOT:
        FROM:
          - VANILLA;BEETROOTS;1;40
          - MMOITEMS;MATERIAL-BEETROOT;1;40
      MMOITEMS;MATERIAL-CARROT:
        FROM:
          - VANILLA;CARROTS;1;50
          - MMOITEMS;MATERIAL-CARROT;1;50
      MMOITEMS;MATERIAL-POTATO:
        FROM:
          - VANILLA;POTATOES;1;60
          - MMOITEMS;MATERIAL-POTATO;1;60