SACK:
  MINING:
    DISPLAY: '&aMining Sack'
    DEFAULT_STORAGE: 10000
    ITEM:
      VANILLA;COBBLESTONE:
        FROM:
          - VANILLA;COBBLESTONE;1;60
          - VANILLA;STONE;3;60
      VANILLA;COAL:
        FROM:
          - VANILLA;COAL;1;80
          - VANILLA;COAL_ORE;1;80
          - VANILLA;COAL_BLOCK;9;80
      VANILLA;IRON_INGOT:
        FROM:
          - VANILLA;IRON_INGOT;1;100
          - VANILLA;IRON_ORE;1;100
          - VANILLA;IRON_BLOCK;9;100
      VANILLA;GOLD_INGOT:
        FROM:
          - VANILLA;GOLD_INGOT;1;120
          - VANILLA;GOLD_ORE;1;120
          - VANILLA;GOLD_BLOCK;9;120
      VANILLA;DIAMOND:
        FROM:
          - VANILLA;DIAMOND;1;140
          - VANILLA;DIAMOND_ORE;1;140
          - VANILLA;DIAMOND_BLOCK;9;140
      VANILLA;EMERALD:
        FROM:
          - VANILLA;EMERALD;1;160
          - VANILLA;EMERALD_ORE;1;160
          - VANILLA;EMERALD_BLOCK;9;160
      VANILLA;QUARTZ:
        FROM:
          - VANILLA;QUARTZ;1;180
          - VANILLA;NETHER_QUARTZ_ORE;1;180
      VANILLA;NETHERITE_INGOT:
        FROM:
          - VANILLA;NETHERITE_INGOT;1;200
          - VANILLA;ANCIENT_DEBRIS;1;200
  FARMING:
    DISPLAY: '&aFarming Sack'
    DEFAULT_STORAGE: 10000
    ITEM:
      VANILLA;WHEAT:
        FROM:
          - VANILLA;WHEAT;1;60
          - VANILLA;WHEAT;1;60
      VANILLA;BEETROOT:
        FROM:
          - VANILLA;BEETROOTS;1;120
          - VANILLA;BEETROOT;1;120
      VANILLA;CARROT:
        FROM:
          - VANILLA;CARROTS;1;240
          - VANILLA;CARROT;1;240
      VANILLA;POTATO:
        FROM:
          - VANILLA;POTATOES;1;360
          - VANILLA;POTATO;1;360