name: LiteSack
version: '${project.version}'
main: net.danh.litesack.LiteSack
api-version: 1.14
authors: [ VoChiDanh ]
commands:
  LiteSack:
    description: Main Command
    aliases:
      - ls
      - lsack