name: LiteSack
version: '${project.version}'
main: net.danh.litesack.LiteSack
api-version: 1.13
authors: [ VoChiDanh ]
libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.5
softdepend:
  - WorldGuard
  - PlaceholderAPI
commands:
  LiteSack:
    description: Main Command
    aliases:
      - ls
      - lsack
permissions:
  ls.admin:
    description: Admin permission
    default: op
  ls.withdraw:
    description: Withdraw permission
    default: true