SETTINGS:
  DEBUG: true
  PREFIX:
    ENABLE: true
    PREFIX: "&7[ &bLiteSack&7 ]"
WORLD_GUARD: #Enable this, you will need set flag ls-mining to allow if you want player mine block ! (Default is deny)
  USE_FLAG: false
FORMAT:
  NUMBER:
    TYPE: true #TYPE LIST: true, false