SETTINGS:
  DEBUG: true
  PREFIX:
    ENABLE: true
    PREFIX: "&7[ &bLiteSack&7 ]"
WORLD_GUARD: #Enable this, you will need set flag ls-mining to allow if you want player mine block ! (Default is deny)
  USE_FLAG: false
FORMAT:
  NUMBER:
    TYPE: true #TYPE LIST: true, false
BLOCK_REGEN:
  ENABLE: true
  USE_SIMPLE_REGEN: true
  BLOCKS:
    STONE:
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    COBBLESTONE:
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    COAL_ORE:
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    COAL_BLOCK:
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    IRON_ORE:
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    IRON_BLOCK:
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    GOLD_ORE:
      - DIAMOND_ORE
      - DIAMOND_BLOCK
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    GOLD_BLOCK:
      - DIAMOND_ORE
      - DIAMOND_BLOCK
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    DIAMOND_ORE:
      - DIAMOND_ORE
      - DIAMOND_BLOCK
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    DIAMOND_BLOCK:
      - DIAMOND_ORE
      - DIAMOND_BLOCK
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    EMERALD_ORE:
      - NETHER_QUARTZ_ORE
      - EMERALD_ORE
      - EMERALD_BLOCK
      - DIAMOND_ORE
      - DIAMOND_BLOCK
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    EMERALD_BLOCK:
      - NETHER_QUARTZ_ORE
      - EMERALD_ORE
      - EMERALD_BLOCK
      - DIAMOND_ORE
      - DIAMOND_BLOCK
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    NETHER_QUARTZ_ORE:
      - ANCIENT_DEBRIS
      - NETHER_QUARTZ_ORE
      - EMERALD_ORE
      - EMERALD_BLOCK
      - DIAMOND_ORE
      - DIAMOND_BLOCK
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE
    ANCIENT_DEBRIS:
      - ANCIENT_DEBRIS
      - NETHER_QUARTZ_ORE
      - EMERALD_ORE
      - EMERALD_BLOCK
      - DIAMOND_ORE
      - DIAMOND_BLOCK
      - GOLD_ORE
      - GOLD_BLOCK
      - IRON_ORE
      - IRON_BLOCK
      - COAL_ORE
      - COAL_BLOCK
      - COBBLESTONE
      - STONE